### ISSUE TITLE
Mejoras

### ISSUE THREAD

**Issue by migueldelmazo** [BbeatrizSI/modulo-1-evaluacion-intermedia-BbeatrizSI#1]
Muy buen trabajo @BbeatrizSI!!!

Aquí tienes unos consejos para mejorar tu ejercicio:

Puntuación: 268 / 347
- [x] HTML > LINK: Debemos tener dos ficheros de estilos importados con un `link`.
- [x] HTML > LINK: El fichero de fuentes debe estar antes que nuestro fichero de estilos para que ningún fichero de estilos externo sobre escriba los nuestros.
- [x] HTML > HEADER: La etiqueta `img` debe tener el atributo `title`.
- [x] HTML > HEADER: Necesitamos al menos una etiqueta `ul`.
- [x] HTML > HEADER: Necesitamos dos etiquetas `li`.
- [x] HTML > HEADER: Necesitamos dos etiquetas `a` en el menu, dentro de los `li`.
- [x] HTML > HEADER: El texto del primer enlace debe ser "Blog". Debemos ponerlo en mayúsculas con CSS.
- [x] HTML > HEADER: El texto del primer enlace debe ser "Contacto". Debemos ponerlo en mayúsculas con CSS.
- [x] HTML > MAIN: El contenido exacto del h1 debe ser "Creando diversidad digital". Debemos poner las primeras letras en mayúsculas con CSS.
- [x] CSS > COLOR: El color del h1 debe ser blanco
- [x] CSS > FONT-SIZE: El tamaño del h1 en móvil debe ser 30px.
- [x] CSS > FONT-SIZE: El tamaño del h1 en tablet debe ser 40px.
- [x] CSS > PADDING: El padding de los enlaces no debería ser 0. Auméntalo para aumentar el área clickable, pero manteniendo los requisitos del diseño.

Es posible que cuando corrijas uno de estos puntos, otros se corrijan solos, ya que unos dependen de otros.

Y recuerda algo muy importante:

- Escribe tu código en inglés.
- Escribe todos los ficheros y carpetas en inglés.
- Los commits tambien tienen que ser en inglés empezando por un verbo en infinitivo.

Ánimo y si tienes cualquier duda avísame!!!

> Este issue ha sido creado automáticamente por ello puede tener algún error, si hay algo que no te enjaca dímelo cuanto antes por favor.

Por favor no cierres este issue, ya lo haremos nosotros.

**Comment by BbeatrizSI** [comment]
Buenos días Miguel!

Como me has dicho por Slack, te indico los items que creo que estaban bien:

-  HTML > LINK: Debemos tener dos ficheros de estilos importados con un link.
-  HTML > HEADER: La etiqueta img debe tener el atributo title.
-  CSS > COLOR: El color del h1 debe ser blanco
-  CSS > FONT-SIZE: El tamaño del h1 en móvil debe ser 30px.
-  CSS > FONT-SIZE: El tamaño del h1 en tablet debe ser 40px.

Esta tarde me pongo a corregir el resto!

Gracias y un saludo!

**Comment by migueldelmazo** [comment]
Hola @BbeatrizSI, te contesto a cada uno de ellos:

- HTML > LINK: Debemos tener dos ficheros de estilos importados con un link: tienes razón pasa de esto.
- HTML > HEADER: La etiqueta img debe tener el atributo title: es cierto que ya tienes un title en la etiqueta madre de esta imagen, entonces no haría falta, pero tampoco sobraría.
- CSS > COLOR: El color del h1 debe ser blanco: el color de tu H1 es negro, el de por defecto de la página. El color del H1 > span es blanco. Visualmente está bien. Pero te recomendaría quitar los 3 span ya que realmente no son necesarios. Si los quitas, tendrás que ponerle el color blanco directamente al H1.
- CSS > FONT-SIZE: El tamaño del h1 en móvil debe ser 30px: Lo mismo que en el caso anterior.
- CSS > FONT-SIZE: El tamaño del h1 en tablet debe ser 40px: Lo mismo que en el caso anterior.

Cualquier duda me dices.

**Comment by BbeatrizSI** [comment]
Vale! Ya lo entiendo, puse los "span" por que es como lo hizo María para controlar las 3 líneas de texto, y por lo tanto mis selectores son H1>span en lugar de solo H1! :)

Muchas gracias!
